// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertImage(arg1, arg2) {
  return window['go']['main']['App']['ConvertImage'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}
