// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

/**
 * função assíncrona que converte imagem para formato desejado
 * @param arg1 Path da imagem sobre a qual deseja converter
 * @param arg2 Extensão a qual deseja que a imagem seja convertida ( ex: "WEBP")
 * @returns informação de conversão {NewPath string ,NewSize number}
 * @param NewPath diretorio temporario da imagem convertida
 * @param NewSize tamanho da imagem convertida em bytes
 */
export function ConvertImage(arg1:string,arg2:string):Promise<models.ConversionInfo>;

export function GetInputPath():Promise<Array<string>>;

export function OpenDirectoryDialog():Promise<string>;

export function ParseImagePaths(arg1:Array<string>):Promise<Array<models.ImageStruct>>;

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
