// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertImage(arg1:string,arg2:string):Promise<string>;

export function OpenFileDialog():Promise<Array<string>>;

export function SelectImage():Promise<Array<main.ImageStruct>>;
