// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ConvertImage(arg1:string,arg2:string):Promise<models.ConversionInfo>;

export function GetInputPath():Promise<Array<string>>;

export function OpenDirectoryDialog():Promise<string>;

export function ParseImagePaths(arg1:Array<string>):Promise<Array<models.ImageStruct>>;

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
